# Generated by Django 3.2.8 on 2021-11-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False, verbose_name='custom title')),
                ('publication_year', models.PositiveIntegerField(verbose_name='custom publication year')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
    ]
