# Generated by Django 3.2.8 on 2021-11-09 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20211104_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book_title',
            field=models.ForeignKey(db_column='book_title', on_delete=django.db.models.deletion.CASCADE, related_name='read_rows', to='blog.book', verbose_name='link to book'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='read_rows', to=settings.AUTH_USER_MODEL, verbose_name='link to user'),
        ),
    ]
