# Generated by Django 3.2.8 on 2021-11-09 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20211109_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(related_name='readers', to='blog.Book'),
        ),
        migrations.AddField(
            model_name='reader',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
