# Generated by Django 3.2.8 on 2021-11-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211109_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='book_title',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='user_id',
            new_name='user',
        ),
    ]
